### Part A: What is an autonomous machine, and what does autonomy mean?
1. > What is an autonomous machine, and what does autonomy mean?

  Autonomous machine refers to a subject that is capable of perceiving the environment and make self decisions based on what it learns from the environment. Usually there is a reward system involved in this process to penalize bad actions in order to establish correct cognize of the environment. Autonomy means capability of making decisions independently in an unknown environment or unfamiliar set of rules without external inputs. It could also mean being able to self driven without external force.

2.  
> a. Classical AI techniques employ trees of decision constructs (if statements, etc.) to achieve some form of "intelligent"-like behavior. An example of this is the famous Eliza AI-based "psychotherapist". What do you feel are the strengths and weaknesses of such an approach? State and explain three such strengths and three weaknesses.

  **Strengths:**
  *   Predictable results, given an input to the system, an output can be predicted by going through the if-else statement chain
  *   Simple algorithm and easy to understand. Chain of if-else statement is less mathematical which makes it easier to track down each steps.
  *   More flexible in terms of corner cases handling. For any corner case, we could simplify add more if-else logic to cover. In this approach, more exceptional cases can be considered which gives us flexibility.

  **Weaknesses:** 
  *    Requires deep understanding of the environment in order to build out an functional system. For example with sequential if else statements, what to do this each steps must be identified upfront and all of logic will remain unchanged during execution.
  *   Limited complexity and not tuneable. As mentioned above, once defined, all logic must remain unchanged which makes it impossible to adapt to more complex changing environment.
  *   Model is not generalized. Although it might perform well for some scenarios, if-else chain cannot be extended to other tasks or areas.
  
  > b. Data Science includes signal processing, adaptive filters, supervised and unsupervised machine learning. These techniques solve the modeling problem from the perspective of the data. That is, they serve to classify signals (data), interpolate signals (data), or extract signal from noise. Comment on how these functions relate to artificial intelligence?

  Artificial intelligence involves creating algorithms to find patterns or clusters or categories in huge amount of data which aligns with data science techniques. These techinques are essential tools to make AI possible. Based on these techniques, AI can perceive existing data to build a model and utilize it to make perdictions on unseen data which makes it "smart". 

  > c. Control theory concerns the development of feedback laws (i.e., control laws) that strive to push a system (the "plant") to a desired state. It does this based on observation of essential characteristics of the plant (the state, or some possibly noisy or lossy observation of the state), and construction of an appropriate feedback signal. How does this tool compare with the prior two, relating to the development of an autonomous system? Explain the similarities and differences from a structural (high level) point of view.

  Control theory focuses on finding equilibrium of an unseen environment based on feedbacks from it. This overlaps with AI in certain areas such as reinforcement learning. As a difference, AI also includes data training based methodologies such as supervised and unsupervised learning. In this case, instead of adapting to environment based on system state and feedback dynamically like control theory and reinforcement learning do, these models are often pre-built and trained on sufficient amount of data and stays unchanged when facing unseen dataset. 






### Part B: Tic Tac Toe


In [1]:
import numpy as np
import math

Creating a Board class, it contains some class methods to interact with tic tac toe board as shown below:

Players will be assigned to be 1 or -1 automatically, first player will be 1.

**reset():** to reset board to original empty state  
**action():** to place on the board  
**check_result(state):** to verify if one has won or if game ties given a state  
**print_board():** to show state of board visually  
**get_state():** to return current state of the board  


In [22]:
class Board():

    board_arr = np.zeros((3,3))
    player = 1
    
    def reset(self):
      # reset board to original empty state
      self.board_arr = np.zeros((3,3))
      self.player = 1

    def action(self, x, y):
      # to place on the board
      # also check if action results in an end game
      if (self.board_arr[x, y] != 0):
        print("Illegal move, please try again!")
        return

      self.board_arr[x, y] = self.player
      self.print_board()
      if self.check_result(self.board_arr) == self.player:
        print("Congratulations {0} win!".format(self.player))
        return
      elif self.check_result(self.board_arr) == 0:
        print("Hey we tie!")
        return

      self.player = self.player * -1
      return

    def check_result(self, arr):
      # verify if one has won or if game ties given a state
      # Check horizontal
      h = arr.sum(axis=0)
      # Check vertical
      v = arr.sum(axis=1)
      # Check diagonal
      d_1 = np.fliplr(arr).diagonal().sum()
      d_2 = np.diagonal(arr).sum()

      if 3 in h or 3 in v or 3 == d_1 or 3 == d_2:
        return 1
      elif -3 in h or -3 in v or -3 == d_1 or -3 == d_2:
        return -1
      elif 0 not in arr:
        return 0
      return 100

    def print_board(self):
      # show state of board visually
      print(self.board_arr)

    def get_state(self):
      # get current state of the board, used by minimax algor
      return self.board_arr
    

I tried to play human to human tic tac toe to test this board class.

In [23]:
board = Board()
board.reset()
board.action(0,0)
board.action(0,1)
board.action(1,0)
board.action(0,2)
board.action(2,0)

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 1. -1.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]]
[[ 1. -1. -1.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]]
[[ 1. -1. -1.]
 [ 1.  0.  0.]
 [ 1.  0.  0.]]
Congratulations 1 win!


In this section, I implemented a Player class using minimax algorithm as playing strategy given a tic tac toe board state. This algorithm will perform exhaustive search on all possible moves from given state, calculate the score/rewards of each move and then pick the move with the best score/reward possible.

One limitation of this implementation now is it assumes this player to be 1.

In [33]:
class Player():

  def __init__(self, player):
    self.player = player
    return

  def get_move(self, board):
    # Compute best next move
    state = board.get_state()
    bestScore = -math.inf
    move = math.inf, math.inf
    for i in range(0,3):
      for j in range(0,3):
        if state[i,j] == 0:
          state[i,j] = self.player
          score = self.minimax(board, state, 0, False)
          state[i,j] = 0
          if score > bestScore:
            bestScore = score
            move = i,j
    return move

  def minimax(self, board, state, depth, isMaximizing):
    # Minimax algor to score each move, and reture the best score
    result = board.check_result(state)
    if result != 100:
      return result 
    
    if isMaximizing:
      bestScore = -math.inf
      for i in range(0,3):
        for j in range(0,3):
          if state[i,j] == 0:
            state[i,j] = self.player
            score = self.minimax(board, state, depth + 1, False)
            state[i,j] = 0
            bestScore = max(score, bestScore)
      return bestScore
    else:
      bestScore = math.inf
      for i in range(0,3):
        for j in range(0,3):
          if state[i,j] == 0:
            state[i,j] = self.player * -1
            score = self.minimax(board, state, depth + 1, True)
            state[i,j] = 0
            bestScore = min(score, bestScore)
      return bestScore

I tested Play class by playing against it.

In [34]:
p1 = Player(1)
board2 = Board()
board2.reset()
board2.print_board()

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [35]:
move = p1.get_move(board2)
board2.action(move[0], move[1])

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [36]:
board2.action(0,1)

[[ 1. -1.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [37]:
move = p1.get_move(board2)
board2.action(move[0], move[1])

[[ 1. -1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  0.]]


In [38]:
board2.action(2,0)

[[ 1. -1.  0.]
 [ 1.  0.  0.]
 [-1.  0.  0.]]


In [39]:
move = p1.get_move(board2)
board2.action(move[0], move[1])

[[ 1. -1.  0.]
 [ 1.  1.  0.]
 [-1.  0.  0.]]


In [40]:
board2.action(2,2)

[[ 1. -1.  0.]
 [ 1.  1.  0.]
 [-1.  0. -1.]]


In [41]:
move = p1.get_move(board2)
board2.action(move[0], move[1])

[[ 1. -1.  0.]
 [ 1.  1.  1.]
 [-1.  0. -1.]]
Congratulations 1 win!


Minimax player seems to make best move every step given a updated board state.